# Generated by Django 2.1 on 2018-08-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crewman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('planet_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('record', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StarshipClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='starship',
            name='starship_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.StarshipClass'),
        ),
        migrations.AddField(
            model_name='crewman',
            name='idiom',
            field=models.ManyToManyField(to='starfleet.Idiom'),
        ),
        migrations.AddField(
            model_name='crewman',
            name='species',
            field=models.ManyToManyField(to='starfleet.Species'),
        ),
        migrations.AddField(
            model_name='crewman',
            name='starship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.Starship'),
        ),
    ]
