# Generated by Django 2.1.5 on 2019-02-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crewman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'crewmen',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=50)),
                ('planet_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.Planet')),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('record', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='crewman',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.Species'),
        ),
        migrations.AddField(
            model_name='crewman',
            name='starship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starfleet.Starship'),
        ),
    ]
